import type { Metadata } from "next";
import "./globals.css";
import { TanstackQueryProvider } from "@/providers/query-provider";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <TanstackQueryProvider>
          <div className="layout">
            <Header />
            <main className="grow">{children}</main>
            <Footer />
          </div>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
